version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres_clip
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: myminiokeythatishouldchange123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set clipable http://minio:9000 minio myminiokeythatishouldchange123;
      /usr/bin/mc mb --ignore-existing clipable/clips;
      exit 0;
      "

  clipable:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clipable
    environment:
      # Backend / App
      MAX_UPLOAD_SIZE: 5GB
      FFMPEG_CONCURRENCY: 1
      FFMPEG_THREADS: 0
      FFMPEG_PRESET: medium
      FFMPEG_TUNE: film
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_IDHASHKEY: mydbidkeythatishouldchange123
      COOKIE_KEY: mycookiekey12345
      S3_BUCKET: clips
      S3_ACCESS: minio
      S3_SECRET: myminiokeythatishouldchange123
      S3_ADDRESS: minio:9000
      S3_SECURE: false
    ports:
      - "3000:3000"  # Nginx dentro do container expõe porta 80
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started

volumes:
  pg_data: {}
  minio_data: {}